import { TGridRowsProp } from "../../../../shared/types/tpTypesImports";

export const table1Rows: TGridRowsProp = [
  {
    id: 1,
    quoteId: 1,
    name: "Abc1",
    rfqDetails: "",
    sellerName: "Abc1",
    bidAmount: "10",
    deliveryTime: "1 days",
    message: "",
    approveReject: "",
    addToCompare: "",
  },
  {
    id: 2,
    quoteId: 2,
    name: "Abc2",
    rfqDetails: "",
    sellerName: "Abc2",
    bidAmount: "20",
    deliveryTime: "2 days",
    message: "Message 2",
    approveReject: "",
    addToCompare: "",
  },
  {
    id: 3,
    quoteId: 3,
    name: "Abc3",
    rfqDetails: "",
    sellerName: "Abc3",
    bidAmount: "30",
    deliveryTime: "3 days",
    message: "",
    approveReject: "",
    addToCompare: "",
  },
  {
    id: 4,
    quoteId: 4,
    name: "Abc4",
    rfqDetails: "",
    sellerName: "Abc4",
    bidAmount: "40",
    deliveryTime: "4 days",
    message: "",
    approveReject: "",
    addToCompare: "",
  },
  {
    id: 5,
    quoteId: 5,
    name: "Abc1",
    rfqDetails: "",
    sellerName: "Abc1",
    bidAmount: "10",
    deliveryTime: "10 days",
    message: "",
    approveReject: "",
    addToCompare: "",
  },
];

export const table2Rows: TGridRowsProp = [
  {
    id: 1,
    quoteId: 1,
    name: "Abc1",
    rfqDetails: "",
    sellerName: "Abc1",
    bidAmount: "10",
    deliveryTime: "1 days",
    message: "",
    approveReject: "",
    removeFromCompare: "",
  },
];
